const fs = require('fs');
let server = fs.readFileSync('server.js', 'utf8');

const regex3 = /function publisherIcon\(value\) \{\n    let hostname = String\(value \|\| ''\)\.toLowerCase\(\);\n    try \{ hostname = new URL\(hostname\.includes\(':\\\/\\\/'\) \? hostname : \`https:\/\/\$\{hostname\}\`\)\.hostname\.toLowerCase\(\); \} catch \(e\) \{ \}\n    if \(hostname\.includes\('tuoitre\.vn'\)\) return 'https:\/\/statictuoitre\.mediacdn\.vn\/web_images\/favicon\.ico';\n    if \(hostname\.includes\('kenh14\.vn'\)\) return 'https:\/\/kenh14cdn\.com\/web_images\/kenh14-favicon\.ico';\n    if \(hostname\.includes\('soha\.vn'\)\) return 'https:\/\/sohanews\.sohacdn\.com\/icons\/soha-32\.png';\n    if \(hostname\.includes\('genk\.vn'\)\) return 'https:\/\/genk\.mediacdn\.vn\/web_images\/genk32\.png';\n    if \(hostname\.includes\('vjst\.vn'\)\) return 'https:\/\/ictv\.1cdn\.vn\/assets\/static\/images\/logo\.png';\n    if \(hostname\.includes\('vtv\.vn'\)\) return 'https:\/\/static\.mediacdn\.vn\/vtv\.vn\/images\/favicon\.ico';\n    if \(hostname\.includes\('doanhnhansaigon\.vn'\)\) return 'https:\/\/dnsg\.1cdn\.vn\/assets\/images\/favicon\.ico';\n    if \(hostname\.includes\('tapchinganhang\.gov\.vn'\)\) return 'https:\/\/tapchinganhang\.gov\.vn\/modules\/frontend\/themes\/tcnh\/images\/favicon\/favicon\.ico\?v=2\.620251216214508';\n    if \(hostname\.includes\('vccinews\.'\)\) return 'https:\/\/vccinews\.com\/images\/logo\.png';\n    if \(hostname\.includes\('haiquanonline\.com\.vn'\)\) return 'https:\/\/www\.google\.com\/s2\/favicons\?domain=customs\.gov\.vn&sz=64';\n    if \(hostname\.includes\('pcworld\.com'\)\) return 'https:\/\/icons\.duckduckgo\.com\/ip3\/pcworld\.com\.ico';\n    return \`https:\/\/www\.google\.com\/s2\/favicons\?domain=\$\{encodeURIComponent\(hostname\)\}&sz=64\`;\n\}/;

if (!regex3.test(server)) {
    console.error("Could not find the publisherIcon block.");
} else {
    server = server.replace(regex3, `function publisherIcon(value) {\n    let hostname = String(value || '').toLowerCase();\n    try { hostname = new URL(hostname.includes('://') ? hostname : \`https://\${hostname}\`).hostname.toLowerCase(); } catch (e) { }\n\n    let sourceHandler = sourceRegistry.getHandler(hostname);\n    if (sourceHandler && sourceHandler.publisherIcon) {\n        let icon = sourceHandler.publisherIcon(hostname);\n        if (icon) return icon;\n    }\n\n    return \`https://www.google.com/s2/favicons?domain=\${encodeURIComponent(hostname)}&sz=64\`;\n}`);
    fs.writeFileSync('server.js', server);
    console.log("Successfully replaced publisherIcon block.");
}
